version: "3.7"
services:
  brka-db:
    image: mysql:8.0.21
    container_name: brka-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=brka